
name:'doge Price'

on: jobs
  push:
    branches: 
      - master
  schedule:
    - cron: '* * * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
   
    -name:  doge
     run: python ./doge.py
          
